#!/bin/bash

set -e

# Note we remove the * so that all the files in the current directory aren't expanded
#BRANCHES=( $(git branch -l | cut -c 3-) )
#
#for i in "${!BRANCHES[@]}"; do 
#  printf "%s  %s\n" "$i" "${BRANCHES[$i]}"
#done
#
#read -p "Checkout: " input

BRANCH=$(git branch -l | cut -c 3- | menu)

echo -en "\nChecking out $BRANCH\n"
if [ "$1" == "-s" ]; then
    git stash
fi

git checkout $BRANCH

if [ "$1" == "-s" ]; then
    git stash pop
fi

