#!/bin/bash

XCWORKSPACE=$(find . -name *.xcworkspace)
VERSION=$1
APP="/Applications/Xcode${VERSION}.app"

if [ -f Package.swift ] 
then
    open -a "$APP" Package.swift
elif [ -d "$XCWORKSPACE" ]
then
    open -a "$APP" "$XCWORKSPACE"
else
    open -a "$APP" "$(find . -name *.xcodeproj)"
fi

